Create api login
VNNam/teatime pull request #5
Opened 2022-01-21 15:17 UTC by Chiendam

có j sai sót cần sửa anh comment giúp em nhé

2022-01-21 18:34 UTC, VNNam requested changes

2022-01-21 18:34 UTC, VNNam commented on database/user.js
> +    return users;
'return users' thì chỉ là object {_id, fullName, email....}
return {user} là object.object - vì hàm này sẽ trả về cả error object để trả về cho client trên FE
khi đó trên route gọi hàm kiểu : `const {user, error} = await users.getUser()`

2022-01-21 18:34 UTC, VNNam commented on controllers/user-controller.js
> +    const user = await users.getOneUser({ email: email});
em thử xử lý check email, compare password, createToken trong database/user.js thành 1 hàm authenticate chẳng hạn.
`createToken({object}, expires) `cũng có thể viết thành hàm dùng chung kiểu utils
hàm này trả về `{token, error}` cho route, mình xử lý kết quả trên res, req

2022-01-21 18:34 UTC, VNNam commented on public/javascripts/user.js
> +        console.log(error);
`error`  thì render lỗi luôn

2022-01-22 03:57 UTC, Chiendam commented on controllers/user-controller.js
> +    const user = await users.getOneUser({ email: email});
Vâng anh để em nghiên cứu thêm vầ cái authenticate này ạ.

2022-02-08 06:03 UTC, closed without merging